### ISSUE TITLE
Question for Betty

### ISSUE THREAD

**Issue by Dahnepfl** [njomeau/zuluzulu#54]
https://github.com/njomeau/zuluzulu/blob/10e3bdfa4567ea1c114298501e2f574d7e8fcaa5/app/src/androidTest/java/ch/epfl/sweng/zuluzulu/MenuAsAuthenticatedTest.java#L38-L41

Hi @betty @dialexo 

Sorry I needed to create an issue to ask the question... 

So, this code is used to connect on the login.
We use the same code in LoginTest.java
We also need to login to test the logout in LogoutTest.java

It's used at least 3 times.
What is **the best** way to refactor if ?
Do I need to create a new class like UtilsTest.java that will only be used for the tests ? With a login() function inside.

Thank you !

Dahn

**Comment by dialexo** [comment]
Yes that sounds reasonable. You can write it as a static function inside a utility class in your androidTest folder.

**Comment by Dahnepfl** [comment]
Ok thank you !
